### ISSUE TITLE
Is License 'MIT' or 'AGPL'?

### ISSUE THREAD

**Issue by ashishsurana** [DxCx/webpack-graphql-server#58]
As [package.json](https://github.com/DxCx/webpack-graphql-server/blob/master/package.json) says license is MIT while [LICENSE](https://github.com/DxCx/webpack-graphql-server/blob/master/LICENSE) file is for AGPL, I was wondering which one is it? 

I hope it's MIT :)

**Comment by DxCx** [comment]
Yep, MIT is fine,
Can you open PR that repleces license file?
GiTHub generate this one when i opened the project..

**Comment by ashishsurana** [comment]
Is this copyright Notice Line is correct ?
```Copyright (c) 2017 Hagai Cohen.```

**Comment by DxCx** [comment]
yep that's me 👍

**Comment by ashishsurana** [comment]
Great! then PR [#59](https://github.com/DxCx/webpack-graphql-server/pull/59) can be merged to have license and README fixed.
Thanks.
